/**
 * Central catalog of machine-readable error codes returned by the API.
 * The web client switches on these — never on error messages.
 */
export const ErrorCodes = {
  // Generic
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INTERNAL: 'INTERNAL',
  RATE_LIMITED: 'RATE_LIMITED',

  // Auth
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  REFRESH_TOKEN_REUSED: 'REFRESH_TOKEN_REUSED',
  CSRF_TOKEN_MISMATCH: 'CSRF_TOKEN_MISMATCH',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',

  // Content & CMS
  LESSON_NOT_PUBLISHED: 'LESSON_NOT_PUBLISHED',
  VERSION_NOT_EDITABLE: 'VERSION_NOT_EDITABLE',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  OPEN_DRAFT_EXISTS: 'OPEN_DRAFT_EXISTS',
  REVIEWER_CANNOT_BE_AUTHOR: 'REVIEWER_CANNOT_BE_AUTHOR',
  SKILLS_REQUIRED_TO_PUBLISH: 'SKILLS_REQUIRED_TO_PUBLISH',
  EMPTY_VERSION_CANNOT_ADVANCE: 'EMPTY_VERSION_CANNOT_ADVANCE',

  // Assessments
  ATTEMPT_LIMIT_REACHED: 'ATTEMPT_LIMIT_REACHED',
  COOLDOWN_ACTIVE: 'COOLDOWN_ACTIVE',
  ATTEMPT_NOT_IN_PROGRESS: 'ATTEMPT_NOT_IN_PROGRESS',
  NO_ITEMS_TO_ATTEMPT: 'NO_ITEMS_TO_ATTEMPT',
  ANSWER_INVALID: 'ANSWER_INVALID',
  SUBMISSION_NOT_PENDING: 'SUBMISSION_NOT_PENDING',
  SCORE_EXCEEDS_POINTS: 'SCORE_EXCEEDS_POINTS',

  // Progress & gating
  GATING_LOCKED: 'GATING_LOCKED',
  LESSON_HAS_QUIZ: 'LESSON_HAS_QUIZ',

  // Projects
  REVIEW_INVALID_TRANSITION: 'REVIEW_INVALID_TRANSITION',
  RESUBMIT_NOT_ALLOWED: 'RESUBMIT_NOT_ALLOWED',
  RUBRIC_INCOMPLETE: 'RUBRIC_INCOMPLETE',
  RUBRIC_SCORE_INVALID: 'RUBRIC_SCORE_INVALID',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
